from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from . import views

urlpatterns = [
    path("auth/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("auth/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("auth/register/", views.RegisterView.as_view(), name="register"),
    path("auth/me/", views.CurrentUserView.as_view(), name="current-user"),
    path("auth/me/update/", views.UpdateProfileView.as_view(), name="update-profile"),
    path("businesses/", views.BusinessListCreateView.as_view(), name="businesses"),
    path("businesses/<int:pk>/", views.BusinessDetailView.as_view(), name="business-detail"),
    path("customers/", views.CustomerListCreateView.as_view(), name="customers"),
    path("customers/<int:pk>/", views.CustomerDetailView.as_view(), name="customer-detail"),
    path("customer-payments/", views.CustomerPaymentListCreateView.as_view(), name="customer-payments"),
    path("customer-payments/<int:pk>/", views.CustomerPaymentDetailView.as_view(), name="customer-payment-detail"),
    path("suppliers/", views.SupplierListCreateView.as_view(), name="suppliers"),
    path("suppliers/<int:pk>/", views.SupplierDetailView.as_view(), name="supplier-detail"),
    path("sales/", views.SaleListCreateView.as_view(), name="sales"),
    path("sales/<int:pk>/", views.SaleDetailView.as_view(), name="sale-detail"),
    path("expense-categories/", views.ExpenseCategoryListCreateView.as_view(), name="expense-categories"),
    path("product-categories/", views.ProductCategoryListCreateView.as_view(), name="product-categories"),
    path("product-categories/<int:pk>/", views.ProductCategoryDetailView.as_view(), name="product-category-detail"),
    path("brands/", views.BrandListCreateView.as_view(), name="brands"),
    path("brands/<int:pk>/", views.BrandDetailView.as_view(), name="brand-detail"),
    path("expenses/", views.ExpenseListCreateView.as_view(), name="expenses"),
    path("expenses/<int:pk>/", views.ExpenseDetailView.as_view(), name="expense-detail"),
    path("stock-counts/rollover/", views.StockRolloverView.as_view(), name="stock-rollover"),
    path("stock-counts/", views.StockCountListCreateView.as_view(), name="stock-counts"),
    path("stock-counts/<int:pk>/", views.StockCountDetailView.as_view(), name="stock-count-detail"),
    path("cashbook/", views.CashBookListCreateView.as_view(), name="cashbook"),
    path("cashbook/<int:pk>/", views.CashBookDetailView.as_view(), name="cashbook-detail"),
    path("receipts/", views.ReceiptListCreateView.as_view(), name="receipts"),
    path("receipts/send_email/", views.SendReceiptEmailView.as_view(), name="receipt-send-email"),
    path("receipts/<int:pk>/", views.ReceiptDetailView.as_view(), name="receipt-detail"),
    path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
    path("reports/sales/", views.SalesReportView.as_view(), name="sales-report"),
    path("reports/expenses/", views.ExpenseReportView.as_view(), name="expense-report"),
    path("reports/profit/", views.ProfitReportView.as_view(), name="profit-report"),
    path("reports/stock/", views.StockReportView.as_view(), name="stock-report"),
    path("members/", views.MemberListCreateView.as_view(), name="members"),
    path("members/<int:pk>/", views.MemberDetailView.as_view(), name="member-detail"),
    path("stations/", views.StationListCreateView.as_view(), name="stations"),
    path("stations/<int:pk>/", views.StationDetailView.as_view(), name="station-detail"),
]
