# Generated by Django 4.2.30 on 2026-08-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_business_settings_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='receipt_footer',
            field=models.CharField(blank=True, help_text="Shown at bottom of receipt e.g. 'Thank you!'", max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='receipt_header',
            field=models.CharField(blank=True, help_text="Extra line shown at top of receipt e.g. 'Welcome!'", max_length=255),
        ),
    ]
