# Generated by Django 4.2.30 on 2026-08-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_business_receipt_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcount',
            name='brand',
            field=models.CharField(choices=[('generic', 'Generic'), ('colgate', 'Colgate'), ('oral_b', 'Oral-B'), ('pepsodent', 'Pepsodent'), ('close_up', 'Close-Up'), ('nivea', 'Nivea'), ('dove', 'Dove'), ('lux', 'Lux'), ('lifebuoy', 'Lifebuoy'), ('ariel', 'Ariel'), ('tide', 'Tide'), ('omo', 'Omo'), ('always', 'Always'), ('whisper', 'Whisper'), ('pampers', 'Pampers'), ('huggies', 'Huggies'), ('nestle', 'Nestlé'), ('coca_cola', 'Coca-Cola'), ('pepsi', 'Pepsi'), ('sprite', 'Sprite'), ('fanta', 'Fanta'), ('kinley', 'Kinley'), ('unilever', 'Unilever'), ('procter', 'Procter & Gamble'), ('other', 'Other')], default='generic', max_length=50),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='category',
            field=models.CharField(choices=[('groceries', 'Groceries'), ('beverages', 'Beverages'), ('snacks', 'Snacks'), ('personal_care', 'Personal Care'), ('household', 'Household'), ('electronics', 'Electronics'), ('clothing', 'Clothing'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
