# Generated by Django 4.2.30 on 2026-08-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_station_member_stations'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='api.station'),
        ),
    ]
