# Generated by Django 4.2.30 on 2026-08-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_customer_credit_limit_customerpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('UGX', 'Ugandan Shilling (UGX)'), ('KES', 'Kenyan Shilling (KSh)'), ('TZS', 'Tanzanian Shilling (TSh)'), ('RWF', 'Rwandan Franc (RWF)'), ('NGN', 'Nigerian Naira (₦)'), ('GHS', 'Ghanaian Cedi (₵)'), ('ZAR', 'South African Rand (R)'), ('ETB', 'Ethiopian Birr (Br)'), ('ZMW', 'Zambian Kwacha (ZK)'), ('XOF', 'West African CFA (CFA)'), ('XAF', 'Central African CFA (FCFA)'), ('MWK', 'Malawian Kwacha (MK)'), ('BIF', 'Burundian Franc (BIF)')], default='UGX', max_length=10),
        ),
        migrations.AlterField(
            model_name='business',
            name='currency_symbol',
            field=models.CharField(default='UGX ', max_length=5),
        ),
    ]
