# Generated by Django 4.2.30 on 2026-08-19 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_new_models'),
        ('api', '0011_alter_business_currency_and_more'),
    ]

    operations = [
    ]
