# Generated by Django 4.2.30 on 2026-09-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20260819_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcount',
            name='barcode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='sku',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='category',
            field=models.CharField(choices=[('building_materials', 'Building Materials'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('tools', 'Tools'), ('paint', 'Paint and Finishes'), ('fasteners', 'Fasteners'), ('roofing', 'Roofing'), ('timber', 'Timber and Boards'), ('safety', 'Safety Equipment'), ('hardware_other', 'Other Hardware'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilograms'), ('g', 'Grams'), ('packets', 'Packets'), ('litres', 'Litres'), ('ml', 'Millilitres'), ('bags', 'Bags'), ('boxes', 'Boxes'), ('bottles', 'Bottles'), ('bundles', 'Bundles'), ('dozen', 'Dozen'), ('meters', 'Meters'), ('rolls', 'Rolls'), ('sheets', 'Sheets'), ('tonnes', 'Tonnes'), ('sets', 'Sets'), ('pairs', 'Pairs'), ('other', 'Other')], default='pcs', max_length=20),
        ),
    ]
