# Generated by Django 4.2.30 on 2026-09-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_stockcount_barcode_stockcount_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Opening cash balance (float) for end-of-day reconciliation', max_digits=12),
        ),
    ]
