# Generated by Django 4.2.30 on 2026-09-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_business_opening_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcount',
            name='brand',
            field=models.CharField(blank=True, default='generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='category',
            field=models.CharField(blank=True, default='other', max_length=100),
        ),
    ]
